# fl-config.yaml
num_epochs: 5
num_clients: 2
num_rounds: 2
batch_size: 16
val_ratio: 0.1
lr: 0.155
data_from_s3: True
heterogeneous_data_set: True
use_gpu: True
energy_weight: 0.5
training_time_weight: 0.3
gpu_weight: 0.2