# fl-config.yaml
num_epochs: 5
num_clients: 2
min_fit_clients: 1
min_evaluate_clients: 1
fraction_fit: 0.5
fraction_eval: 0.5
num_rounds: 2
round_timeout: 5000
batch_size: 16
val_ratio: 0.1
lr: 0.155
data_from_s3: True
heterogeneous_data_set: True
use_gpu: True
energy_weight: 0.5
training_time_weight: 0.3
gpu_weight: 0.2